# Generated by Django 2.2.13 on 2020-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeblocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
