# Generated by Django 2.2.13 on 2020-07-23 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeblocks', '0002_auto_20200722_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TimeBlockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timeblock',
            name='timeBlockList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timeblocks.TimeBlockList'),
        ),
    ]
