# Generated by Django 2.2.13 on 2020-07-23 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeblocks', '0003_auto_20200723_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblocklist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
