# Generated by Django 2.2.13 on 2020-07-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeblocks', '0004_auto_20200723_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblocklist',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timeblocklist',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
