# Generated by Django 2.2.13 on 2020-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeblocks', '0005_auto_20200724_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblocklist',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
