# Generated by Django 2.2.13 on 2020-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeblocks', '0006_auto_20200724_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblocklist',
            name='color',
            field=models.CharField(choices=[('#eeeeee', 'gray'), ('#ff0000', 'red'), ('#0000ff', 'blue'), ('#00ff00', 'green'), ('#000000', 'black'), ('#ffffff', 'white'), ('#ffcc00', 'yellow')], default='white', max_length=7),
        ),
    ]
