# Generated by Django 2.2.13 on 2020-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0004_auto_20200807_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
