# Generated by Django 2.2.13 on 2020-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0005_auto_20200829_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
