# Generated by Django 2.2.13 on 2020-08-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0006_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='the_date',
        ),
    ]
