# Generated by Django 2.2.13 on 2020-08-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0007_auto_20200831_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
