# Generated by Django 2.2.13 on 2020-09-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0008_auto_20200831_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='the_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='the_start_time',
            field=models.TimeField(null=True),
        ),
    ]
