# Generated by Django 2.2.13 on 2020-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0009_auto_20200901_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#eeeeee', 'gray'), ('#ff0000', 'red'), ('#0000ff', 'blue'), ('#00ff00', 'green'), ('#000000', 'black'), ('#ffffff', 'white'), ('#7E8F7C', 'khaki')], default='gray', max_length=7),
        ),
    ]
