# Generated by Django 2.2.13 on 2020-09-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0010_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
