# Generated by Django 2.2.13 on 2020-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0011_auto_20200901_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#eeeeee', 'gray'), ('#ff0000', 'red'), ('#0000ff', 'blue'), ('#00ff00', 'green'), ('#000000', 'black'), ('#ffffff', 'white'), ('#7E8F7C', 'khaki')], default='white', max_length=7),
        ),
    ]
