# Generated by Django 2.2.13 on 2020-09-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0012_auto_20200902_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#fc5353', 'red'), ('#ff0000', 'orange'), ('#0000ff', 'yellow'), ('#00ff00', 'green'), ('#67b4fc', 'blue'), ('#b467fc', 'purple'), ('#ffffff', 'white')], default='white', max_length=7),
        ),
    ]
