# Generated by Django 2.2.13 on 2020-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0015_auto_20200903_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#fc5353', 'red'), ('#f7a902', 'orange'), ('#ffcc00', 'yellow'), ('#76fc58', 'green'), ('#67b4fc', 'blue'), ('#b467fc', 'purple'), ('#fcd5ab', 'salmon')], default='white', max_length=7),
        ),
    ]
