# Generated by Django 2.2.13 on 2020-07-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockit', '0002_auto_20200721_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='length',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
