# Generated by Django 2.2.13 on 2020-07-21 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockit', '0003_auto_20200721_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.date(2020, 7, 21)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.date(2020, 7, 21)),
        ),
    ]
