# Generated by Django 2.2.13 on 2020-07-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockit', '0015_auto_20200722_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
