# Generated by Django 2.2.13 on 2020-07-27 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blockit', '0016_auto_20200723_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 17, 45, 36, 553766, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 17, 45, 36, 553748, tzinfo=utc)),
        ),
    ]
