# Generated by Django 2.2.13 on 2020-08-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockit', '0077_auto_20200806_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
