# Generated by Django 2.2.13 on 2020-09-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockit', '0079_auto_20200902_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
